version: '3.9'

services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-impact}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-impact}
      POSTGRES_DB: ${POSTGRES_DB:-impact_dev}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 10

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: postgresql+psycopg://impact:impact@db:5432/impact_dev
      SECRET_KEY: ${SECRET_KEY:-changeme}
      ACCESS_TOKEN_EXPIRE_MINUTES: "60"
      STRIPE_API_KEY: ${STRIPE_API_KEY:-}
      STRIPE_WEBHOOK_SECRET: ${STRIPE_WEBHOOK_SECRET:-}
      OPENAI_API_KEY: ${OPENAI_API_KEY:-}
      ELASTIC_CLOUD_ID: ${ELASTIC_CLOUD_ID:-}
      ELASTIC_API_KEY: ${ELASTIC_API_KEY:-}
      BACKEND_CORS_ORIGINS: ${BACKEND_CORS_ORIGINS:-http://localhost:5173}
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy

volumes:
  db_data: {}


