version: '3.8'
services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: impact
      POSTGRES_USER: impact
      POSTGRES_PASSWORD: impact
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U impact"]
      interval: 5s
      timeout: 5s
      retries: 10

  backend:
    build: ./backend
    environment:
      DATABASE_URL: postgresql+psycopg://impact:impact@db:5432/impact
      SECRET_KEY: ${SECRET_KEY:-changeme}
      ACCESS_TOKEN_EXPIRE_MINUTES: 60
      BACKEND_CORS_ORIGINS: "http://localhost"
      STRIPE_API_KEY: ${STRIPE_API_KEY:-}
      STRIPE_WEBHOOK_SECRET: ${STRIPE_WEBHOOK_SECRET:-}
      OPENAI_API_KEY: ${OPENAI_API_KEY:-}
    depends_on:
      db:
        condition: service_healthy

  web:
    build:
      context: .
      dockerfile: Dockerfile.web
      args:
        - VITE_API_BASE_URL=http://localhost/api
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  postgres_data:


