// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://srjqnyobijmroogxhidt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNyanFueW9iaWptcm9vZ3hoaWR0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ3NjkyODQsImV4cCI6MjA3MDM0NTI4NH0.C4AYMZOwTBySaRwTD6qQmjc14INtMA1TWEyeCENn37k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});